// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOptions() {
  return window['go']['main']['App']['GetOptions']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ReadTag() {
  return window['go']['main']['App']['ReadTag']();
}

export function StartTagWatcher() {
  return window['go']['main']['App']['StartTagWatcher']();
}

export function StopTagWatcher() {
  return window['go']['main']['App']['StopTagWatcher']();
}

export function ValidateColor(arg1) {
  return window['go']['main']['App']['ValidateColor'](arg1);
}

export function WriteTag(arg1) {
  return window['go']['main']['App']['WriteTag'](arg1);
}
