// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetOptions():Promise<main.OptionsResponse>;

export function GetVersion():Promise<string>;

export function ReadTag():Promise<main.TagData>;

export function StartTagWatcher():Promise<void>;

export function StopTagWatcher():Promise<void>;

export function ValidateColor(arg1:string):Promise<string>;

export function WriteTag(arg1:main.WriteRequest):Promise<void>;
