name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.github/**'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
      
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2

      - name: Update Version in Code
        run: |
          echo "Updating version to ${{ steps.gitversion.outputs.semVer }}"
          sed -i 's/version = ".*"/version = "${{ steps.gitversion.outputs.semVer }}"/g' cmd/app/main.go
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cmd/app/main.go
          git commit -m "chore: update version to ${{ steps.gitversion.outputs.semVer }}" || echo "No changes to commit"

      - name: Build
        env:
          VERSION: ${{ steps.gitversion.outputs.semVer }}
        run: |
          GOOS=darwin GOARCH=amd64 go build -o dist/cfs-spool-mac-amd64 ./cmd/app
          GOOS=darwin GOARCH=arm64 go build -o dist/cfs-spool-mac-arm64 ./cmd/app
          GOOS=linux GOARCH=amd64 go build -o dist/cfs-spool-linux-amd64 ./cmd/app
          GOOS=windows GOARCH=amd64 go build -o dist/cfs-spool-windows-amd64.exe ./cmd/app

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: v${{ steps.gitversion.outputs.semVer }}
          name: Release v${{ steps.gitversion.outputs.semVer }}
          draft: false
          prerelease: false
          files: |
            dist/cfs-spool-mac-amd64
            dist/cfs-spool-mac-arm64
            dist/cfs-spool-linux-amd64
            dist/cfs-spool-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Version Update
        run: git push
